Develop
kosei-iino/HelloGit pull request #3
Opened 2020-11-14 03:38 UTC by kosei-iino

各所修正
変数の宣言修正
演算子の変更

2020-11-16 00:49 UTC, kouki-iwahara reviewed
コメントしましたのでご確認ください。

2020-11-16 00:49 UTC, kouki-iwahara commented on index.html
> +const EleBtn = document.getElementById('btn');
命名の先頭は小文字にしましょう。
`eleBtn`
他も同様です。
以下の記事に書いてあることを初めは意識すると良いかと思うので、参考にしてください。
https://qiita.com/codeship_tech/items/22a657a758af5f5ef067

2020-11-16 00:49 UTC, kouki-iwahara commented on index.html
> +        let EleErr = document.createElement('p');
cosntで定義できます。

2020-11-16 00:49 UTC, kouki-iwahara commented on index.html
> +<html lang='en'>
htmlの文字列は`""`で囲みましょう。

2020-11-16 12:12 UTC, kosei-iino commented on index.html
> +const EleBtn = document.getElementById('btn');
コメントありがとうございます。
修正致しました。

2020-11-16 12:13 UTC, kosei-iino commented on index.html
> +        let EleErr = document.createElement('p');
コメントありがとうございます。
同一のプロパティに2度以上入れない場合はconstで良いということですね。
修正致しました。

2020-11-16 12:13 UTC, kosei-iino commented on index.html
> +<html lang='en'>
上記修正致しました。

2020-11-17 01:31 UTC, myzktkyk requested changes
1点指摘をしております。

2020-11-17 01:31 UTC, myzktkyk commented on index.html
> +        eleNums.appendChild(eleErr);
エラーチェックの場合は以下のような感じで `return` を書いて
「一番最後の else がエラーがない時」を避けるように記述することが多いです。
```suggestion
        eleNums.appendChild(eleErr);
        return;
```

2020-11-17 04:03 UTC, kosei-iino commented on index.html
> +        eleNums.appendChild(eleErr);
上記修正致しました。
よろしくお願いします

2020-11-22 01:56 UTC, kouki-iwahara reviewed
コメントしましたのでご確認ください！

2020-11-22 01:56 UTC, kouki-iwahara commented on index.html
>      else{
このelseは不要（elseで囲まなくても同じ処理が走る）かと思いますがいかがでしょうか？

2020-11-22 04:44 UTC, kosei-iino commented on index.html
>      else{
すみません。
前回のプルリクをクローズしてしまっていた所為もあり、返答を開示できませんでした。
以下返信内容を貼り付けます。

＞isNaNで少数チェックができているかと思いますがいかがでしょうか？
＞以下が参考になるかと。
＞https://qiita.com/taku-0728/items/329e0bee1c49b7ce7cd1
確かにisNanの列で小数がfalseとなっているのを確認しましたが、
実際にテストとして小数を入力して動かしたところ、isNanで出力されるはずの文字列ではなく、後続の小数チェックの文字列が出力されたり、

小数チェックをコメントアウトして、動かすとそのまま処理が流れてしまうことを確認できました。

ご確認よろしくお願いします。

2020-11-23 02:04 UTC, kouki-iwahara commented on index.html
>      else{
>小数チェックをコメントアウトして、動かすとそのまま処理が流れてしまうことを確認できました。

なるほどです。
こちらはいかがでしょうか？
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger

2020-11-23 08:14 UTC, kosei-iino commented on index.html
>      else{
ありがとうございます。
上記処理で更新いたしました。

よろしくお願いします。

2020-11-23 08:19 UTC, merged